#ifndef SSCARDSERVICE_SANDONG_GLOBAL_H
#define SSCARDSERVICE_SANDONG_GLOBAL_H



#if defined(SSCARDSERVICE_SANDONG_LIBRARY)
#  define SSCARDSERVICE_SANDONG_EXPORT Q_DECL_EXPORT
#else
#  define SSCARDSERVICE_SANDONG_EXPORT Q_DECL_IMPORT
#endif

#endif // SSCARDSERVICE_SANDONG_GLOBAL_H
