/****************************************************************************
**
** Metadata for DVTLDCamOCXLib generated by dumpcpp v5.15.2 using
** d:\qt\5.15.2\msvc2019\bin\dumpcpp.exe {01E21292-EE9C-4DFB-B436-B4BE239D794A}
** from the type library D:\DVTLiveDetect\DvtLivedetect\DVTLDCamOCX.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_DVTLDCAMOCXLIB_NOINLINES
#include "dvtldcamocxlib.h"
#include <OAIdl.h>

using namespace DVTLDCamOCXLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[35];
    char stringdata0[426];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 29, 0),
QT_MOC_LITERAL(1, 30, 9, 0),
QT_MOC_LITERAL(2, 40, 0, 0),
QT_MOC_LITERAL(3, 41, 4, 0),
QT_MOC_LITERAL(4, 46, 6, 0),
QT_MOC_LITERAL(5, 53, 4, 0),
QT_MOC_LITERAL(6, 58, 4, 0),
QT_MOC_LITERAL(7, 63, 15, 0),
QT_MOC_LITERAL(8, 79, 4, 0),
QT_MOC_LITERAL(9, 84, 6, 0),
QT_MOC_LITERAL(10, 91, 4, 0),
QT_MOC_LITERAL(11, 96, 4, 0),
QT_MOC_LITERAL(12, 101, 8, 0),
QT_MOC_LITERAL(13, 110, 11, 0),
QT_MOC_LITERAL(14, 122, 17, 0),
QT_MOC_LITERAL(15, 140, 18, 0),
QT_MOC_LITERAL(16, 159, 11, 0),
QT_MOC_LITERAL(17, 171, 11, 0),
QT_MOC_LITERAL(18, 183, 12, 0),
QT_MOC_LITERAL(19, 196, 10, 0),
QT_MOC_LITERAL(20, 207, 10, 0),
QT_MOC_LITERAL(21, 218, 10, 0),
QT_MOC_LITERAL(22, 229, 10, 0),
QT_MOC_LITERAL(23, 240, 13, 0),
QT_MOC_LITERAL(24, 254, 18, 0),
QT_MOC_LITERAL(25, 273, 7, 0),
QT_MOC_LITERAL(26, 281, 7, 0),
QT_MOC_LITERAL(27, 289, 27, 0),
QT_MOC_LITERAL(28, 317, 17, 0),
QT_MOC_LITERAL(29, 335, 19, 0),
QT_MOC_LITERAL(30, 355, 11, 0),
QT_MOC_LITERAL(31, 367, 13, 0),
QT_MOC_LITERAL(32, 381, 21, 0),
QT_MOC_LITERAL(33, 403, 8, 0),
QT_MOC_LITERAL(34, 412, 12, 0)
    },
    "DVTLDCamOCXLib::_DDVTLDCamOCX\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0AboutBox\0CloseCamera\0EndLiveDectection\0FaceCompareByImage\0"
    "szFileName1\0szFileName2\0GetImageData\0iDataClass\0GetProduct\0GetVersion\0"
    "OpenCamera\0SnapshotImage\0StartLiveDetection\0timeout\0control\0DVTLDCamOCXLib::DVTLDCamOCX\0"
    "Event Interface 1\0_DDVTLDCamOCXEvents\0Interface 0\0_DDVTLDCamOCX\0LiveDetectStatusEvent\0"
    "nEventID\0nFrameStatus\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_DVTLDCamOCXLib___DDVTLDCamOCX[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    13, 14, // methods
    1, 116, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 79, 2, 5,
    7, 1, 88, 2, 5,
    9, 3, 91, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 98, 2, 9,
    13, 0, 99, 2, 9,
    14, 0, 100, 2, 9,
    15, 2, 101, 2, 9,
    18, 1, 106, 2, 9,
    20, 0, 109, 2, 9,
    21, 0, 110, 2, 9,
    22, 0, 111, 2, 9,
    23, 0, 112, 2, 9,
    24, 1, 113, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Double, QMetaType::QString, QMetaType::QString, 16, 17,
    QMetaType::QString, QMetaType::Int, 19,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::Int, QMetaType::Int, 25,

 // properties: name, type, flags
    26, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

_DDVTLDCamOCX::_DDVTLDCamOCX(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject _DDVTLDCamOCX::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DVTLDCamOCXLib___DDVTLDCamOCX, nullptr, nullptr, nullptr }
};

void *_DDVTLDCamOCX::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "DVTLDCamOCXLib::_DDVTLDCamOCX"))
        return static_cast<void*>(const_cast<_DDVTLDCamOCX*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DVTLDCamOCXLib__DVTLDCamOCX[] = {

 // content:
    7, // revision
    27,  // classname
    2, 14, // classinfo
    14, 18, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    28, 29, 
    30, 31, 

// signal: name, argc, parameters, tag, flags
    32, 2, 88, 2, 5,
    1, 4, 93, 2, 5,
    7, 1, 102, 2, 5,
    9, 3, 105, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 112, 2, 9,
    13, 0, 113, 2, 9,
    14, 0, 114, 2, 9,
    15, 2, 115, 2, 9,
    18, 1, 120, 2, 9,
    20, 0, 123, 2, 9,
    21, 0, 124, 2, 9,
    22, 0, 125, 2, 9,
    23, 0, 126, 2, 9,
    24, 1, 127, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 33, 34,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Double, QMetaType::QString, QMetaType::QString, 16, 17,
    QMetaType::QString, QMetaType::Int, 19,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::Int, QMetaType::Int, 25,

    0 // eod
};

DVTLDCamOCX::DVTLDCamOCX(QWidget *parent, Qt::WindowFlags f) :
    QAxWidget(parent, f)
{
    setControl(QStringLiteral("{01e21292-ee9c-4dfb-b436-b4be239d794a}"));
}

const QMetaObject DVTLDCamOCX::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DVTLDCamOCXLib__DVTLDCamOCX, nullptr, nullptr, nullptr }
};

void *DVTLDCamOCX::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "DVTLDCamOCXLib::DVTLDCamOCX"))
        return static_cast<void*>(const_cast<DVTLDCamOCX*>(this));
    return QAxWidget::qt_metacast(_clname);
}

