/* soapScrzServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.139 for facereconize.h

gSOAP XML Web services tools
Copyright (C) 2000-2025, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapScrzServiceSoapBindingProxy_H
#define soapScrzServiceSoapBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC ScrzServiceSoapBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'ScrzServiceSoapBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in facereconize.h, if any
        /// Construct a proxy with new managing context
        ScrzServiceSoapBindingProxy();
        /// Copy constructor
        ScrzServiceSoapBindingProxy(const ScrzServiceSoapBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        ScrzServiceSoapBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        ScrzServiceSoapBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        ScrzServiceSoapBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        ScrzServiceSoapBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        ScrzServiceSoapBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        ScrzServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~ScrzServiceSoapBindingProxy();
        /// Initializer used by constructors
        virtual void ScrzServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual ScrzServiceSoapBindingProxy *copy();
        /// Copy assignment
        ScrzServiceSoapBindingProxy& operator=(const ScrzServiceSoapBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'allJK' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int allJK(_ns1__allJK *ns1__allJK, _ns1__allJKResponse &ns1__allJKResponse) { return this->allJK(NULL, NULL, ns1__allJK, ns1__allJKResponse); }
        /// Web service synchronous operation 'allJK' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int allJK(const char *soap_endpoint_url, const char *soap_action, _ns1__allJK *ns1__allJK, _ns1__allJKResponse &ns1__allJKResponse) { return this->send_allJK(soap_endpoint_url, soap_action, ns1__allJK) || this->recv_allJK(ns1__allJKResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_allJK' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_allJK(const char *soap_endpoint_url, const char *soap_action, _ns1__allJK *ns1__allJK);
        /// Web service asynchronous operation 'recv_allJK' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_allJK(_ns1__allJKResponse &ns1__allJKResponse);
        //
        /// Web service synchronous operation 'getInfo' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getInfo(_ns1__getInfo *ns1__getInfo, _ns1__getInfoResponse &ns1__getInfoResponse) { return this->getInfo(NULL, NULL, ns1__getInfo, ns1__getInfoResponse); }
        /// Web service synchronous operation 'getInfo' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getInfo(const char *soap_endpoint_url, const char *soap_action, _ns1__getInfo *ns1__getInfo, _ns1__getInfoResponse &ns1__getInfoResponse) { return this->send_getInfo(soap_endpoint_url, soap_action, ns1__getInfo) || this->recv_getInfo(ns1__getInfoResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getInfo' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getInfo(const char *soap_endpoint_url, const char *soap_action, _ns1__getInfo *ns1__getInfo);
        /// Web service asynchronous operation 'recv_getInfo' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getInfo(_ns1__getInfoResponse &ns1__getInfoResponse);
    };
#endif
